### ISSUE TITLE
TaxCode and TaxRate don't have save() or update() methods

### ISSUE THREAD

**Issue by jasonhoward64** [ej2/python-quickbooks#297]

**Comment by jasonhoward64** [comment]
Running tax_code.save(qb=client), for example, produces the following error: 'TaxRate' object has no attribute 'save'

**Comment by ej2** [comment]
This is not an issue. The Tax Code and Tax Rate objects do not have a save method because QBO does not allow you to create them directly. They have to be created using Tax Service. See the [QBO docs ](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/taxservice) for more information.
